const css = `
.dmc-root,.dmc-picker{--dmc-line:color-mix(in srgb,currentColor 15%,transparent);--dmc-soft:color-mix(in srgb,currentColor 4%,transparent);--dmc-accent:#3263d8;--dmc-success:#1f6c3d;--dmc-error:#b92d39;--dmc-pending:#87520a;color:inherit;font:inherit;line-height:1.5}
body[data-ds-dark-theme] .dmc-root,body[data-ds-dark-theme] .dmc-picker{--dmc-accent:#96b7ff;--dmc-success:#8cdaad;--dmc-error:#ffa0a8;--dmc-pending:#f3c77d}
.dmc-root{width:100%;min-width:0;max-width:1100px;margin:0 auto;container-type:inline-size;padding:4px 0 24px;box-sizing:border-box}
.dmc-root *, .dmc-picker *{box-sizing:border-box}
.dmc-root h2{font-size:24px;line-height:1.3;margin:4px 0}.dmc-root h3{font-size:16px;margin:20px 0 12px}.dmc-root p{margin:8px 0}.dmc-eyebrow{font-size:12px;color:var(--dmc-accent);font-weight:650;letter-spacing:.08em}
.dmc-root button,.dmc-root .dmc-button,.dmc-picker button{border:1px solid var(--dmc-line);border-radius:9px;padding:8px 12px;background:transparent;color:inherit;cursor:pointer;font:inherit;font-size:13px;text-decoration:none;white-space:normal}
.dmc-root button:hover,.dmc-picker button:hover{background:var(--dmc-soft)}.dmc-root button:disabled,.dmc-picker button:disabled{opacity:.45;cursor:default}.dmc-root :focus-visible,.dmc-picker :focus-visible{outline:2px solid var(--dmc-accent);outline-offset:2px}
.dmc-root .dmc-primary,.dmc-picker .dmc-primary{background:var(--dmc-accent);color:white;border-color:transparent}.dmc-root .dmc-link{border:0;text-decoration:underline;padding:3px 0;background:none;color:inherit}
body[data-ds-dark-theme] .dmc-root .dmc-primary,body[data-ds-dark-theme] .dmc-picker .dmc-primary{color:#182644}
.dmc-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.dmc-muted{opacity:.65;font-size:12px;overflow-wrap:anywhere}.dmc-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:20px 0}.dmc-summary>div{border:1px solid var(--dmc-line);border-radius:12px;padding:12px;background:var(--dmc-soft);display:flex;flex-direction:column}.dmc-summary strong{font-size:24px;font-weight:650}.dmc-summary small{font-size:11px;opacity:.65}
.dmc-tabs,.dmc-filters{display:flex;gap:4px;flex-wrap:wrap}.dmc-tabs{border-bottom:1px solid var(--dmc-line);margin-bottom:20px;padding-bottom:10px}.dmc-tabs button{border:0}.dmc-tabs button[aria-selected=true],.dmc-filters button[aria-pressed=true]{background:var(--dmc-soft);color:var(--dmc-accent);font-weight:650}.dmc-tabs~[hidden]{display:none}
.dmc-toolbar{display:grid;grid-template-columns:1fr 1fr;gap:12px}.dmc-field{display:flex;flex-direction:column;gap:6px;font-size:12px;min-width:0}.dmc-root input:not([type=checkbox]),.dmc-root select,.dmc-picker select,.dmc-picker input{width:100%;min-width:0;border:1px solid var(--dmc-line);background:transparent;color:inherit;border-radius:8px;padding:9px 10px;font:inherit;font-size:13px}.dmc-root option,.dmc-picker option{color:CanvasText;background:Canvas}.dmc-fields{padding:0;margin:14px 0;border:0;display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,210px),1fr));gap:14px}.dmc-filter-row{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:16px 0}.dmc-filters button{font-size:12px;padding:6px 12px}
.dmc-model-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,290px),1fr));gap:10px}.dmc-card{min-width:0;border:1px solid var(--dmc-line);border-radius:12px;padding:16px;margin-bottom:10px;overflow-wrap:anywhere}.dmc-model-list .dmc-card{margin:0}.dmc-model-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.dmc-model-heading b{font-size:15px}.dmc-root .dmc-star{border:0;padding:0 5px;font-size:24px;line-height:1.2;color:var(--dmc-accent)}.dmc-model-controls{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-top:16px}.dmc-effort{font-size:11px;display:flex;align-items:center;gap:8px;min-width:0}.dmc-effort select{width:80px}.dmc-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center;min-width:0}.dmc-success{color:var(--dmc-success);font-size:12px;overflow-wrap:anywhere}.dmc-error{color:var(--dmc-error);font-size:12px;overflow-wrap:anywhere}.dmc-pending{color:var(--dmc-pending);font-size:12px}.dmc-empty{padding:30px;text-align:center;opacity:.7}
.dmc-saved{display:flex;flex-direction:column;gap:7px;padding:16px;background:var(--dmc-soft);border:1px solid var(--dmc-line);border-radius:12px;overflow-wrap:anywhere}.dmc-saved small,.dmc-saved span{font-size:12px;opacity:.65}.dmc-savebar{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;border-top:1px solid var(--dmc-line);padding:16px 0 4px;margin-top:20px}.dmc-savebar>div:first-child,.dmc-savebar>span{flex:1 1 180px}.dmc-savebar .dmc-actions{flex:0 1 auto}.dmc-check{display:flex;gap:8px;align-items:center;font-size:13px;padding:8px 0}.dmc-check input{accent-color:var(--dmc-accent)}
.dmc-source-row{display:flex;align-items:flex-start;gap:12px;flex-wrap:wrap}.dmc-source-icon{width:36px;height:36px;border-radius:10px;background:var(--dmc-soft);display:grid;place-items:center;flex-shrink:0;font-weight:650}.dmc-source-main{flex:1 1 180px;min-width:0}.dmc-source-main p{margin:2px 0 6px}.dmc-root code{font-size:11px;word-break:break-all}.dmc-badges{display:flex;gap:6px;flex-wrap:wrap;margin-top:12px}.dmc-badges span{border-radius:6px;background:var(--dmc-soft);font-size:11px;padding:4px 7px}.dmc-body{border-top:1px solid var(--dmc-line);margin-top:14px;padding-top:10px}.dmc-callout{font-size:12px;background:var(--dmc-soft);padding:12px;border-radius:10px;overflow-wrap:anywhere}.dmc-settings{margin-bottom:18px}.dmc-footer{border-top:1px solid var(--dmc-line);padding-top:14px;margin-top:20px}
@container (max-width:430px){.dmc-toolbar{grid-template-columns:1fr}.dmc-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.dmc-head{flex-wrap:wrap}.dmc-filter-row{align-items:flex-start;flex-direction:column}.dmc-savebar .dmc-actions{width:100%}.dmc-actions button{flex:1}.dmc-card{padding:12px}}
.dmc-picker{position:relative;min-width:0;font-size:12px}.dmc-picker>button{font-size:12px;padding:5px 8px;max-width:300px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dmc-picker-panel{position:absolute;bottom:calc(100% + 8px);right:0;width:360px;max-width:calc(100vw - 32px);max-height:min(560px,75vh);overflow:auto;border:1px solid var(--dmc-line);border-radius:12px;background:var(--surface-primary,Canvas);color:CanvasText;box-shadow:0 12px 40px #0002;padding:14px;z-index:100}.dmc-picker-panel h3{font-size:14px;margin:0 0 8px}.dmc-picker-panel .dmc-fields{display:grid;gap:10px;margin:10px 0}.dmc-picker-panel .dmc-model-pick{display:flex;justify-content:space-between;gap:8px;width:100%;text-align:left;margin:5px 0;font-size:12px}.dmc-picker-panel .dmc-model-pick[aria-pressed=true]{background:var(--dmc-soft);color:var(--dmc-accent)}.dmc-picker-panel .dmc-filters button{font-size:11px;padding:5px 8px}.dmc-picker-panel .dmc-actions{justify-content:flex-end;margin-top:12px}.dmc-picker-panel p{margin:8px 0}
`
export function installStyles(): () => void {
  const element = document.createElement('style')
  element.dataset.modelConsole = 'true'
  element.textContent = css
  document.head.append(element)
  return () => element.remove()
}
